;; Split emacs customizations generated by emacs into separate file
(setq custom-file "~/.emacs.d/emacs-customizations.el")
(load custom-file 'noerror)


;; Add and enable MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives
             '("melpamarmalade" . "http://marmalade-repo.org/packages/") t)

(package-initialize)

;; add your modules path
(add-to-list 'load-path "~/.emacs.d/custom/")
(add-to-list 'load-path "~/.emacs.d/external/")

;; To update the package list
;; checks if there are no package archives, which should only be the case  when emacs starts first time emacs in a machine.
(when (not package-archive-contents)
    (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(setq use-package-verbose t)

(use-package diminish
  :ensure t)

(eval-after-load "eldoc"
  '(diminish 'eldoc-mode))

;; load your modules
(require 'ui)
(require 'evil-editing)
(require 'conf-which-key)
(require 'keybindings)
(require 'pairs-and-brackets)
(require 'misc)
(require 'conf-backup)
(require 'conf-ibuffer)
(require 'search-and-find)
(require 'mod-lisp)
(require 'completions-and-snippets)
(require 'mod-markdown)
(require 'mod-tex)
(require 'mod-org)
(require 'mod-haskell)
(require 'vc)
(require 'conf-projectile)
